trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: counties
    type: object
    default:
      - 001|1|CountyA
      - 002|1|CountyB
      - 003|2|CountyC

variables:
  County: ''
  CountyId: ''
  CountyName: ''
  FarmId: ''
  Prefix: ''

steps:
  - script: |
      case $(Build.SourceBranchName) in
        main)
          echo "##vso[task.setvariable variable=Prefix;]prd"
          ;;
        stage)
          echo "##vso[task.setvariable variable=Prefix;]stage"
          ;;
        *)
          echo "##vso[task.setvariable variable=Prefix;]nprd"
          ;;
      esac
    displayName: 'Set Prefix'
  - script: echo "$(Prefix)"
    displayName: 'Display Prefix'
  - script: echo "$(Build.SourceBranchName)"
    displayName: 'Display Source Branch Name'
  - script: echo "${{parameters.environment}}"
    displayName: 'Display Environment'
  - ${{ each county in parameters.counties }}:
    - script: |
        IFS='|'
        read -a countyInfo <<< "${{county}}"
        echo "CountyId: ${countyInfo[0]}"
        echo "CountyName : ${countyInfo[2]}"
        echo "FarmId : ${countyInfo[1]}"
        echo "##vso[task.setvariable variable=County;]${{county}}"
        echo "##vso[task.setvariable variable=CountyId;]${countyInfo[0]}"
        echo "##vso[task.setvariable variable=FarmId;]${countyInfo[1]}"
        echo "##vso[task.setvariable variable=CountyName;]${countyInfo[2]}"
      displayName: 'Execute County: ${{ county }}'
    - script: echo "${{county}}"
      displayName: 'Display ${{county}}'
    - script: echo "$(County)"
      displayName: 'Display County'
    - script: echo "$(CountyId)"
      displayName: 'Display CountyId'
    - script: echo "$(CountyName)"
      displayName: 'Display CountyName'
    - script: echo "$(FarmId)"
      displayName: 'Display FarmId'
