trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: CountyId
    type: string
    default: ''
  - name: CountyName
    type: string
    default: ''
  - name: FarmId
    type: string
    default: ''
  - name: Prefix
    type: string
    default: ''

steps:
  - script: |
      echo "Inside pipeline-release.yml"
      echo "County Id: ${{CountyId}}"
      echo "County Name: ${{CountyName}}"
      echo "Farm Id: ${{FarmId}}"
      echo "Prefix: ${{Prefix}}"
    displayName: 'Display Parameters Received in Release Pipeline'
  - template: /pipeline-template-bicep.yml
    parameters:
      prefix: ${{Prefix}}
      farmId: ${{FarmId}}
      countyId: ${{CountyId}}
      countyName: ${{CountyName}}
  - template: /pipeline-template-deploy.yml
    parameters:
      prefix: ${{Prefix}}
      farmId: ${{FarmId}}
      countyId: ${{CountyId}}
      countyName: ${{CountyName}}
