trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: CountyId
    type: string
    default: ''
  - name: CountyName
    type: string
    default: ''
  - name: FarmId
    type: string
    default: ''
  - name: Prefix
    type: string
    default: ''
  - name: ImageLabel
    type: string
    default: ''
  - name: Test
    type: object
    default:
      - 001|1|CountyA
      - 002|1|CountyB
      - 003|2|CountyC

steps:
  - script: |
      echo "Inside pipeline-release.yml"
      echo "County Id: ${{parameters.CountyId}}"
      echo "County Name: ${{parameters.CountyName}}"
      echo "Farm Id: ${{parameters.FarmId}}"
      echo "Prefix: ${{parameters.Prefix}}"
      echo "Image Label: ${{parameters.ImageLabel}}"
    displayName: 'Display Parameters Received in Release Pipeline'
  - template: /pipeline-template-bicep.yml
    parameters:
      prefix: ${{parameters.Prefix}}
      farmId: ${{parameters.FarmId}}
      countyId: ${{parameters.CountyId}}
      countyName: ${{parameters.CountyName}}
  - template: /pipeline-template-deploy.yml
    parameters:
      prefix: ${{parameters.Prefix}}
      farmId: ${{parameters.FarmId}}
      countyId: ${{parameters.CountyId}}
      countyName: ${{parameters.CountyName}}
      imageLabel: ${{parameters.ImageLabel}}
  - ${{ each site in parameters.Test }}:
    - script: |
        IFS='|'
        read -a siteInfo <<< "${{site}}"
        echo "${{site}}" >> $(Build.ArtifactStagingDirectory)/manifest.txt

        echo "CountyId: ${siteInfo[0]}"
        echo "CountyName : ${siteInfo[2]}"
        echo "FarmId : ${siteInfo[1]}"
        echo "##vso[task.setvariable variable=site;]${{site}}"
        echo "##vso[task.setvariable variable=siteId;]${siteInfo[2]}"
        echo "##vso[task.setvariable variable=siteFarmId;]${siteInfo[1]}"
        echo "##vso[task.setvariable variable=siteName;]${siteInfo[0]}"
        echo "##vso[task.setvariable variable=ResourceGroupName;]-ctcms-df${siteInfo[1]}-app-rg"
      displayName: 'SITE: ${{ site }}'
